main: pl.ibcgames.mclvotifier.Votifier
name: MCL-Votifier-OG
authors: [kaziu687, kisi69, notalexnoyle]
website: https://github.com/true-og/MCL-Votifier-OG
version: '${version}'
api-version: '${apiVersion}'
commands:
  mcl-test:
    description: Test vote reward's commands
    usage: /mcl-test
  mcl-reward:
    description: Claim reward for vote at mc-list.org
    usage: /mcl-reward
  mcl-vote:
    description: See voting website address
    usage: /mcl-vote
